### PR TITLE
mapToChange inline fix

### PR DESCRIPTION
**Pull request by 6hundreds**
Hi, thanks for amazing project
Here the small commit for fixing issue#36. Will glad to make smth more valuable for domic project

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Why did you close it? :)

**Comment by 6hundreds** [comment]
I have some strange trouble with CLA agreement. I'm accepted it, verified commit author name&email (it's correct) but still can't pass CLA check with "An author in one of the commits has no associated github account" :(

**Comment by artem-zinnatullin** [comment]
I think this is due to first commit being done with different author, I'd recommend to squash into one commit with correct author and force push

**Comment by 6hundreds** [comment]
@artem-zinnatullin Now it's looks like build failed due accepting licenses at build agent.

**Comment by artem-zinnatullin** [comment]
uhh, yeah, lemme fix it in separate pr, sorry

```
> Failed to install the following Android SDK packages as some licences have not been accepted.
```

**Comment by artem-zinnatullin** [comment]
https://github.com/lyft/domic/pull/43, please rebase once that pr lands 🙃

**Comment by 6hundreds** [comment]
Yeah, now it's done =) Thx

**Comment by artem-zinnatullin** [comment]
Cool, thx for contribution 👍

**Pull request merged**
